# Use some descriptive name
name: Minimal workflow for Python using Docker image

# The events that trigger this workflow.
on:
  push:
  # We added this so we can run the workflow manually as well without making changes.
  workflow_dispatch:

# One or more jobs to run.
jobs:
  # `build`, the name of the job, is arbitrary, you can use any word for the name of your jobs.
  build:
    # runs-on: the platform (operating system) the job runs on.
    runs-on: ubuntu-latest
    # The docker image, by default from https://hub.docker.com/ to use.
    container:
      image: python:3.14

    # steps - Each step can have a name and it must have a run.
    steps:
      - name: Look around
        # When excuting more command we can use a pipeline | to indicate this.
        # The goal of the following commands is to show you what is included in the
        # specific Docker image.
        run: |
          uname -a
          python -V

